language: ruby
rvm:
  - ruby-head
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
script: bundle exec rspec --format documentation
cache: bundler
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: eb44970f9efc497fb68c6ec1ce051dea530776b6a5bbe75e57734625f761ac86
